# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 420fd40c47fca8075c29d8f74b3f74326ae4af513f595da61a393792852e525a331292c1afa00bf801ccd457306f1053c3625a3b6e11854a27aa4c8b0247f367

test:
  secret_key_base: 5ab98dc16a7e584be3c8efd7ffa4eb916fb508fa6c5b54ae8f17ad1d3106f1fd3c9302d3704db0b2f1c88edf65fb78264406ade5b869b85e81f245cc0b0744a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
